# -*- coding: utf-8 -*-
"""FinalNER_Base.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PClUZhKjPhwUU_wm1II-lRh6BWDab0V4
"""

!pip install spacy==2.3.1

import random
import spacy
import json

from google.colab import drive
drive.mount('/content/drive')

import json

train_data=[]

f = open("/content/drive/MyDrive/Resume Parser/data.json", encoding="utf-8")

for i in f:
    ents_list = []
    main_data = []
    ents_dict = dict()
    data = json.loads(i)
    content=data["content"]
    main_data.append(content)
    for annotation in data["annotation"]:
      ents=[]
      ents_dict = dict()
      label = annotation['label']
      points = annotation['points']
      if label==["Designation"] or label==["Companies worked at"] or label==["Skills"]:
        start = points[0]['start']
        end = points[0]['end']
        ents.append(start)
        ents.append(end)
        ents.append(label[0])
        ents_list.append(ents)
        ents_dict['entities'] = ents_list
        main_data.append(ents_dict)
    f_main_data = [main_data[0], main_data[-1]]
    if type(f_main_data[1]) == dict:
      train_data.append(f_main_data)
f.close()

print(train_data)
#with open('training_data.json', 'w', encoding="utf-8") as f:
    #f.write(str(train_data))

def clean_entities(training_data):
    
    clean_data = []
    for text, annotation in training_data:
        
        entities = annotation.get('entities')
        entities_copy = entities.copy()
        
        # append entity only if it is longer than its overlapping entity
        i = 0
        for entity in entities_copy:
            j = 0
            for overlapping_entity in entities_copy:
                # Skip self
                if i != j:
                    e_start, e_end, oe_start, oe_end = entity[0], entity[1], overlapping_entity[0], overlapping_entity[1]
                    # Delete any entity that overlaps, keep if longer
                    if ((e_start >= oe_start and e_start <= oe_end) \
                    or (e_end <= oe_end and e_end >= oe_start)) \
                    and ((e_end - e_start) <= (oe_end - oe_start)):
                        entities.remove(entity)
                j += 1
            i += 1
        clean_data.append((text, {'entities': entities}))
                
    return clean_data

data = clean_entities(train_data)

print(data)

def train_spacy(data, iterations):
    TRAIN_DATA = data
    nlp = spacy.blank('en')
    if 'ner' not in nlp.pipe_names:
        ner = nlp.create_pipe('ner')
        nlp.add_pipe(ner, last=True)
    for _, annotations in TRAIN_DATA:
        for ent in annotations.get('entities'):
            ner.add_label(ent[2])
    other_pipes = [pipe for pipe in nlp.pipe_names if pipe != 'ner']
    with nlp.disable_pipes(*other_pipes):
        optimizer = nlp.begin_training()
        for itn in range(iterations):
            print('Starting iteration ' + str(itn))
            random.shuffle(TRAIN_DATA)
            losses = {}
            for text, annotations in TRAIN_DATA:
                nlp.update(
                    [text],
                    [annotations],
                    drop=0.2,
                    sgd=optimizer,
                    losses=losses
                )
                print(losses)
    return nlp

import warnings
warnings.filterwarnings('ignore')
warnings.warn('DelftStack')
warnings.warn('Do not show this message')

nlp = train_spacy(data, 10)

text = """SHIKHAR SRIVASTAVA
NOIDA · 9911828145
Email · shikhars371@gmail.com


I'm Blockchain And Software developer having 8+ years sole experience of developing Web and mobile apps. I'm expert in developing customised blockchain software solutions.

My experience possess years of experience and have developed a large number of different blockchain applications for various enterprises. Our blockchain services and products cover Smart Contract Development, Digital Tokens, Private Blockchain Development, White-label Cryptocurrency Exchange Software and more.



Expertise:

Multi-Currency Payment Processing
Wallet development
Forking coin
Exchange Trading
Token Creation
Token Distribution
Hosting and Administration
ICO Landing Page
Custom Token Rules
Multi-Sig Wallets
web3
Ethers,
Bitcoin,
Ethereum,
Tron
EOS
CryptoKitties
NFT (Non Fungible Token) (Ethereum and BSC)
Solidity
Audit Smat-Contract
BSC- BINANCE-SMART-CHAIN


AdBank (Adbank is a revolutionary advertising platform and is the protocol that BLADE is built on.)
https://adbank.network/

Xinfin (Hybrid private blockchain network)
www.xinfin.org

PocketInns  (A gambling website)
http://www.pocketinns.io/

ROC ICO (also built wallet)
https://coinmarketcap.com/currencies/rasputin-online-coin/

Freedom digital marketing website
https://top-digitalmarketing.com/

GBC 
ICO and website
https://twitter.com/goldbitscoin?lang=en

Future1Coin
https://future1coin.com/

Coinfluence - ICO dashboard & website
https://www.coinfluence.org/

Smart contracts gist link
https://gist.github.com/shikhars371
Github Repo:
https://github.com/shikhars371?tab=repositories
Website:
https://seekware.in/

UbetsCoin
https://www.ubetscoin.com/
Explorer - https://explorer.ubetscoin.com/
Wallet - https://wallet.ubetscoin.com/


Tokenized Asset
https://www.funder1.co.uk/tokenized/

Mobile (IOS Android) erc20 tokens & ethereum Wallet
ERC20 App

https://play.google.com/store/apps/details?id=multi.erc20.devgenesis.token.wallet

https://itunes.apple.com/us/app/ethereum-erc20tokens-wallet/id1386738877?ls=1&mt=8

Arcade Game Blockchain Implementation-
https://arcade.catbread.club/#

Booking Portal
https://www.indiaonroaming.com/

Food ordering app
https://www.chowcall.net/

Property Booking website
https://www.lavitrineduneuf.fr/

Electric Vehicle website
https://rec.quelpromoteur.fr/


NFT website (SODA Factory)
https://www.sodafactory.io/
https://opensea.io/collection/soda-pass

In-house NFT
https://flynft.io/

NFT generetative algo
https://opensea.io/collection/mr-everybody
https://mreverybody.sodafactory.io/

NFT generative algo website
https://mint.sodafactory.io/
https://opensea.io/collection/viento-en-contra

NFT minting website
https://possessions.sodafactory.io/
https://opensea.io/collection/mr-everybody-possessions-collection


main net - http://158.247.212.105:81/
test net - http://141.164.52.212:81/
Snail house NFT marketplace supporting 721 and 1155 protocol on polygon and Ethereum (in development)

https://mint.revolue.com/
http://revolue.com/
https://opensea.io/collection/revolue
Revolue NFT

Decentralize dex like Uniswap on Ethereum Rinkeby test network
https://eloquent-bombolone-93f2c3.netlify.app/


Education

ISC (2010)
ST. BASIL’S, SCHOOL
2014
B.TECH (IT), UPTU

SKILLS
•	React
•	Angular
•	Nodejs
•	Laravel 
•	PHP	•	PHP
•	Blockchain
•	Vuejs
•	Nextjs

"""

nlp.to_disk('/content/drive/MyDrive/Resume Parser/nlp_ner_model')

nlp_model = spacy.load('/content/drive/MyDrive/Resume Parser/nlp_ner_model')

doc = nlp_model(text)
for ent in doc.ents:
    print(f"{ent.label_.upper():{30}}-{ent.text}")